name: build and deploy spring-api
on:
  push:
    branches: [deploy-aws-ec2]
  pull_request:
    branches: [deploy-aws-ec2]

jobs:
  build:
    name: build and deploy spring-api
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: build the app
        run: |
          mvn clean
          mvn install -DskipTests --file /pom.xml
          

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ec2-demo:latest

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ec2-demo:latest
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ec2-demo:latest
      - name: Run docker container
        run: docker run -d  -p 8080:8080 --name ec2-demo-container